# Could not generate automatically.
# Expected elements: {
  "columns": [
    "EXECUTING_SERVER",
    "METRICS_TYPE",
    "CLIENT",
    "ORDER_NUMBER",
    "Select values",
    "BILLING_COUNTRY",
    "STARTDATE",
    "OBJECT_COPY",
    "METRICS_VALUE",
    "FLOW_STATUS_CODE",
    "REPOSITORY_DIRECTORY",
    "CHANNEL_ID",
    "BILLING_SITE_STATUS",
    "oracle_con-1",
    "METRICS_DATE",
    "LINES_REJECTED",
    "OBJECT_REVISION",
    "METRICS_CODE",
    "SHIPPING_ADDRESS1",
    "LOGDATE",
    "DEPDATE",
    "BILLING_CITY",
    "SHIPPING_SITE_STATUS",
    "REPLAYDATE",
    "Transformation44",
    "SHIPPING_CITY",
    "FILENAME",
    "ACCOUNT_NAME",
    "constant",
    "OBJECT_NAME",
    "String operations",
    "LOG_DATE",
    "Calculator",
    "STEPNAME",
    "EXECUTING_USER",
    "ROOT_CHANNEL_ID",
    "ID_BATCH",
    "LINES_INPUT",
    "OUTPUT_BUFFER_ROWS",
    "SOLD_TO_CUSTOMER",
    "ERRORS",
    "LOG_FIELD",
    "INPUT_BUFFER_ROWS",
    "METRICS_SUBJECT",
    "oracle_con_1",
    "TRANSNAME",
    "PARENT_CHANNEL_ID",
    "Filter rows",
    "SEQ_NR",
    "LOGGING_OBJECT_TYPE",
    "LINES_OUTPUT",
    "LINES_WRITTEN",
    "ORG_ID",
    "LINES_READ",
    "LINES_UPDATED",
    "METRICS_DESCRIPTION",
    "STATUS",
    "ORDERED_DATE",
    "BILLING_ADDRESS1",
    "Table input",
    "OBJECT_ID",
    "STEP_COPY",
    "SHIPPING_COUNTRY",
    "ENDDATE",
    "Table output"
  ],
  "filters": [
    "N\n        roundupvalue\n        >\n        \n        \n          constant\n          Integer\n          5000\n          -1\n          0\n          N\n          ####0;-####0"
  ],
  "joins": [],
  "calculations": [
    "roundupvalue\n      ROUND_1\n      ORG_ID\n      \n      \n      Integer\n      -1\n      -1\n      N"
  ],
  "string_ops": []
}
